### PR TITLE
Die not confess

### LINKED ISSUE #19: MooX::StrictConstructor incompatible with sensitive fields
If `MooX::StrictConstructor` catches an extra field, it dumps a stack trace with `confess`. While this is helpful for debugging, it can create insecurities, eg.

```
$ cat test.pl
use strict;
use warnings;

package Foo;

use Moo;
use MooX::StrictConstructor;

has password => ( is  => 'ro' );

package main;

Foo->new(
    password    => "THIS SHOULD NOT BE IN STACK TRACE!",
    extra_field => 1,
);
$ perl test.pl
Found unknown attribute(s) passed to the constructor: extra_field at (eval 12) line 49.
        Foo::new("Foo", "password", "THIS SHOULD NOT BE IN STACK TRACE!", "extra_field", 1) called at test.pl line 13
```

Would you be amenable to/have any suggestions for a patch to fix this?

### PR DESCRIPTION
**Pull request by jrubinator**
Fixes #19 

Thanks again for your suggestions and your patience!

### CODE REVIEW

File: lib/MooX/StrictConstructor.pm [hunk 1]
```diff
@@ -24,6 +24,12 @@ Simply loading this module makes your constructors "strict". If your
 constructor is called with an attribute init argument that your class does not
 declare, then it dies. This is a great way to catch small typos.
 
+If you would like your exceptions to contain a stack trace, you can enable
```
Comment (hartzell) [inline lib/MooX/StrictConstructor.pm]: Wordsmithing, I'd change this section to just be:

> Your application can use L<Carp::Always> to generate stack traces on C<warn> and C<die>, see its documentation for additional details.

**Comment by hartzell** [comment]
I fixed one last typo (eg. -> e.g. so that the pod spelling test passed) by hand, merged and pushed.  Did a release, please see if it works for you.

Thanks!
